# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a2adfdb8503487ca224dfa848678d9b239ce3f52fe696ae53180dcc86c58535e47857a98a2dacd4b9ba9843b5af86bfe89147587b95b67fb5a6c03a897cb939

test:
  secret_key_base: 61677f821af13f93941d01b505d6ea89f1574744f0b50293a770eac24d3b4f866e2cd3ffc9b6108b7791871262e8db746150beede2f09c982bafbb68a40e1f31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
